// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { FoodSpawnSchedule } from "./food_spawn_schedule_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `food_spawn_schedule`.
 *
 * Obtain a handle from the [`foodSpawnSchedule`] property on [`RemoteTables`],
 * like `ctx.db.foodSpawnSchedule`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.foodSpawnSchedule.on_insert(...)`.
 */
export class FoodSpawnScheduleTableHandle {
  tableCache: TableCache<FoodSpawnSchedule>;

  constructor(tableCache: TableCache<FoodSpawnSchedule>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<FoodSpawnSchedule> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `scheduledId` unique index on the table `food_spawn_schedule`,
   * which allows point queries on the field of the same name
   * via the [`FoodSpawnScheduleScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.foodSpawnSchedule.scheduledId().find(...)`.
   *
   * Get a handle on the `scheduledId` unique index on the table `food_spawn_schedule`.
   */
  scheduledId = {
    // Find the subscribed row whose `scheduledId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): FoodSpawnSchedule | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduledId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: FoodSpawnSchedule) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: FoodSpawnSchedule) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: FoodSpawnSchedule) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: FoodSpawnSchedule) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: FoodSpawnSchedule, newRow: FoodSpawnSchedule) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: FoodSpawnSchedule, newRow: FoodSpawnSchedule) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
